build-sys: Disable -Werror
This breaks build in gcc >= 4.8. And it breaks in places it's not
relevant to upstream. Just disable -Werror and select which warnings
we are going to fix without having to fix all of them.

audio/gstsbcenc.c: In function 'gst_sbc_enc_get_type':
/usr/include/glib-2.0/glib/gmacros.h:162:53: error: typedef '_GStaticAssertCompileTimeAssertion_0' locally defined but not used [-Werror=unused-local-typedefs]
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                                     ^